---

  - name: Prepare directory to store

    local_action:
      module:       file
      path:         "{{ mysqlc_archive_dir }}"
      state:        directory



  - name: Download MySQL Cluster archive

    local_action:
      module:       get_url
      url:          "{{ mysqlc_archive_url }}"
      dest:         "{{ mysqlc_archive_dir }}"



  - name: Upload and extract MySQL Cluster archive

    become:         yes

    unarchive:
      src:          "{{ mysqlc_archive_path }}"
      dest:         "{{ mysqlc_extract_dir }}"
      creates:      "{{ mysqlc_install_dir }}"



  - name: Create symbolic link of MySQL Cluster

    become:         yes

    file:
      src:          "{{ mysqlc_install_dir }}"
      dest:         "{{ mysqlc_base_dir }}"
      state:        link



  - name: Create MySQL Cluster user

    become:           yes

    user:
      name:           "{{ mysqlc_user }}"
      uid:            "{{ mysqlc_uid }}"
      home:           "{{ mysqlc_base_dir }}"
      createhome:     no
      shell:          /sbin/nologin
