---

  - name: Create data directory for mgmt node

    become:         yes

    file:
      path:         "{{ mysqlc_config.ndb_mgmd.data_dir }}"
      owner:        "{{ mysqlc_user }}"
      group:        "{{ mysqlc_group }}"
      state:        directory



  - name: Create config.ini

    become:         yes

    template:
      src:          config.ini.j2
      dest:         "{{ mysqlc_config.ndb_mgmd.config_file }}"
      owner:        "{{ mysqlc_user }}"
      group:        "{{ mysqlc_group }}"



  - name: Create service script for mgmt node

    become:         yes

    template:
      src:          init.ndb-mgmd.j2
      dest:         /etc/init.d/{{ mysqlc_service_name.ndb_mgmd }}
      owner:        root
      group:        root
      mode:         0755


  - name: Enable MySQL mgmt node service on boot

    become:         yes

    service:
      name:         "{{ mysqlc_service_name.ndb_mgmd }}"
      enabled:      yes



  - name: Open mgmt node port

    become:         yes

    lineinfile:
      dest:         /etc/sysconfig/iptables
      insertafter:  ^:OUTPUT
      line:         -A INPUT -p tcp -m state --state NEW --dport {{ mysqlc_config.ndb_mgmd.port }} -j ACCEPT

    notify:         Restart iptables
