
mysqlc_archive_url:             https://dev.mysql.com/get/Downloads/MySQL-Cluster-7.4/mysql-cluster-gpl-7.4.11-linux-glibc2.5-x86_64.tar.gz
mysqlc_archive_dir:             /tmp/tarball/mysqlc
mysqlc_archive_filename:        "{{ mysqlc_archive_url | basename }}"
mysqlc_archive_filepath:        "{{ mysqlc_archive_dir }}/{{ mysqlc_archive_filename }}"
mysqlc_archive_checksum:        md5:08826a3af20406de05e4993ab0c01bf1

mysqlc_extract_dir:             /usr/local
mysqlc_install_dir:             '{{ mysqlc_extract_dir }}/{{ mysqlc_archive_filename | regex_replace("\.tar\.gz", "") }}'
mysqlc_base_dir:                '{{ mysqlc_extract_dir }}/mysqlcluster'

mysqlc_deploy_dir:              /ext/mysqlcluster
mysqlc_config_dir:              '{{ mysqlc_deploy_dir }}/config'

mysqlc_user:                    mysqlc
mysqlc_group:                   mysqlc
mysqlc_uid:                     5001

mysqlc_profile_file:            /etc/profile.d/mysqlc.sh
mysqlc_sysconfig_file:          /etc/sysconfig/mysqlc

mysqlc_service_name:
  ndb_mgmd:                     ndb-mgmd
  ndbd:                         ndbd


mysqlc_config:

  ndb_mgmd:
    config_file:                "{{ mysqlc_config_dir }}/config.ini"
    data_dir:                   "{{ mysqlc_deploy_dir }}/ndb_mgmd"
    port:                       1186

  ndbd:
    config_file:                "{{ mysqlc_config_dir }}/my.data.cnf"
    data_dir:                   "{{ mysqlc_deploy_dir }}/ndb_data"
    no_of_replicas:             1
    port:                       63132

  mysqld:
    data_dir:                   "{{ mysqlc_deploy_dir }}/mysqld"



# ----------------------------
# host information in config.ini
# ----------------------------
mysqlc_nodes:

  mgmt:
    - ip_address:               192.168.0.10
      node_id:                  49

  # node_group must be assigned from 0.
  data:
    - ip_address:               192.168.0.10
      node_id:                  1
      node_group:               0

  sql:
    - ip_address:               192.168.0.10
      node_id:                  51

  # if you need no api node,
  # set either begin_id and end_id to zero.
  api:
    begin_id:                   52
    node_count:                 2
