---

  - name: Prepare directory to store Erlang and depending packages

    local_action:
      module:   file
      path:     "{{ erlang_rpms_dir }}"
      state:    directory


  - name: download Erlang packages with dependencies

    local_action:
      module:   get_url
      url:      "{{ item }}"
      dest:     "{{ erlang_rpms_dir }}/{{ item | basename }}"

    with_items:
      - "{{ erlang_rpms }}"


  - name: Upload Erlang and depending packages

    copy:
      src:      "{{ erlang_rpms_dir }}"
      dest:     "{{ erlang_rpms_dir | dirname }}"
