#
# This playbook will download packages at localhost, 
# upload the packages to remote hosts and then install them.
#
# So it will perform the following procedure:
#   1.  Create directory to store packages
#   2.  Install wget command to add Erlang repository if not installed
#   3.  Add Erlang Solution repository
#   4.  Download RabbitMQ package and dependencies
#   5.  Upload the packages to remote hosts
#   6.  Install them
#

---

  - name: Prepare directory to store RabbitMQ and depending packages

    local_action:
      module:       file
      path:         "{{ rabbitmq_rpms_dir }}"
      state:        directory



  - name: Install wget command

    become:         yes

    local_action:
      module:       yum
      name:         wget



  - name: Add Erlang Solution repository

    become:         yes

    local_action:
      module:       yum
      name:         "{{ erlang_solutions_rpm }}"
      state:        installed



  - name: Add gpg key for RabbitMQ to RPM DB

    become:         yes

    local_action:
      module:       rpm_key
      key:          "{{ rabbitmq_gpg_key }}"



  - name: Download RabbitMQ package with dependencies

    become:         yes

    local_action:
      module:       yumdownload
      name:         rabbitmq-server
      downloaddir:  "{{ rabbitmq_rpms_dir }}"



  - name: Upload RabbitMQ and depending packages

    copy:
      src:          "{{ rabbitmq_rpms_dir }}"
      dest:         "{{ rabbitmq_rpms_dir | dirname }}"



  - name: Install RabbitMQ and depending packages

    become:         yes

    yum:
      name:         "{{ item }}"

    with_fileglob:
      - "{{ rabbitmq_rpms_dir }}/*.rpm"



  - name: Open access port for RabbitMQ

    become:             yes

    lineinfile:
      dest:             /etc/sysconfig/iptables
      insertafter:      "^:OUTPUT"
      line:             "-A INPUT -i {{ rabbitmq_iptables.in }} -p tcp -m state --state NEW --dport {{ item }} -j ACCEPT"

    with_items:         "{{ rabbitmq_iptables.dest_ports }}"

    notify:
      -                 restart iptables



  - name: Enable RabbitMQ server on boot

    become:             yes

    service:
      name:             rabbitmq-server
      state:            started
      enabled:          yes
